modLoader="javafml"
loaderVersion="[35,)"
updateJSONURL="https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/skyblockcatia_version.json"
issueTrackerURL="https://github.com/SteveKunG/SkyBlockcatia/issues"
license="MIT License"

[[mods]]
modId="skyblockcatia"
version="${file.jarVersion}"
displayName="SkyBlockcatia"
description="Useful Hypixel Skyblock features, QOL and In-game API Viewer!"
credits="Credit to LeaPhant, matdoes for inspiration to make In-game API Viewer possible"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skyblockcatia"
authors="SteveKunG"
logoFile="logo.png"

[[dependencies.skyblockcatia]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.skyblockcatia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.skyblockcatia]]
    modId="stevekungs_lib"
    mandatory=true
    versionRange="[4.0.2,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.skyblockcatia]]
    modId="indicatia"
    mandatory=false
    versionRange="[4.0.2,)"
    ordering="NONE"
    side="CLIENT"